services:
  - type: web
    name: magsasa-card-staging
    env: python
    buildCommand: pip install -r requirements_production.txt
    startCommand: gunicorn app_production:app
    envVars:
      - key: FLASK_ENV
        value: staging
      - key: DATABASE_URL
        fromDatabase:
          name: magsasa-card-db
          property: connectionString
